(cl:defpackage explorer-srv
  (:use )
  (:export
   "ROBOTPOSITION"
   "<ROBOTPOSITION-REQUEST>"
   "ROBOTPOSITION-REQUEST"
   "<ROBOTPOSITION-RESPONSE>"
   "ROBOTPOSITION-RESPONSE"
   "GETCOST"
   "<GETCOST-REQUEST>"
   "GETCOST-REQUEST"
   "<GETCOST-RESPONSE>"
   "GETCOST-RESPONSE"
   "DISTANCEFROMROBOT"
   "<DISTANCEFROMROBOT-REQUEST>"
   "DISTANCEFROMROBOT-REQUEST"
   "<DISTANCEFROMROBOT-RESPONSE>"
   "DISTANCEFROMROBOT-RESPONSE"
  ))

