// Generated by gencpp from file explorer/DistanceFromRobot.msg
// DO NOT EDIT!


#ifndef EXPLORER_MESSAGE_DISTANCEFROMROBOT_H
#define EXPLORER_MESSAGE_DISTANCEFROMROBOT_H

#include <ros/service_traits.h>


#include <explorer/DistanceFromRobotRequest.h>
#include <explorer/DistanceFromRobotResponse.h>


namespace explorer
{

struct DistanceFromRobot
{

typedef DistanceFromRobotRequest Request;
typedef DistanceFromRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DistanceFromRobot
} // namespace explorer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::explorer::DistanceFromRobot > {
  static const char* value()
  {
    return "0ac1e84f911cdd938f7a90afd5ead5e4";
  }

  static const char* value(const ::explorer::DistanceFromRobot&) { return value(); }
};

template<>
struct DataType< ::explorer::DistanceFromRobot > {
  static const char* value()
  {
    return "explorer/DistanceFromRobot";
  }

  static const char* value(const ::explorer::DistanceFromRobot&) { return value(); }
};


// service_traits::MD5Sum< ::explorer::DistanceFromRobotRequest> should match 
// service_traits::MD5Sum< ::explorer::DistanceFromRobot > 
template<>
struct MD5Sum< ::explorer::DistanceFromRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::explorer::DistanceFromRobot >::value();
  }
  static const char* value(const ::explorer::DistanceFromRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::explorer::DistanceFromRobotRequest> should match 
// service_traits::DataType< ::explorer::DistanceFromRobot > 
template<>
struct DataType< ::explorer::DistanceFromRobotRequest>
{
  static const char* value()
  {
    return DataType< ::explorer::DistanceFromRobot >::value();
  }
  static const char* value(const ::explorer::DistanceFromRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::explorer::DistanceFromRobotResponse> should match 
// service_traits::MD5Sum< ::explorer::DistanceFromRobot > 
template<>
struct MD5Sum< ::explorer::DistanceFromRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::explorer::DistanceFromRobot >::value();
  }
  static const char* value(const ::explorer::DistanceFromRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::explorer::DistanceFromRobotResponse> should match 
// service_traits::DataType< ::explorer::DistanceFromRobot > 
template<>
struct DataType< ::explorer::DistanceFromRobotResponse>
{
  static const char* value()
  {
    return DataType< ::explorer::DistanceFromRobot >::value();
  }
  static const char* value(const ::explorer::DistanceFromRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXPLORER_MESSAGE_DISTANCEFROMROBOT_H
