// Generated by gencpp from file explorer/RobotPositionResponse.msg
// DO NOT EDIT!


#ifndef EXPLORER_MESSAGE_ROBOTPOSITIONRESPONSE_H
#define EXPLORER_MESSAGE_ROBOTPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace explorer
{
template <class ContainerAllocator>
struct RobotPositionResponse_
{
  typedef RobotPositionResponse_<ContainerAllocator> Type;

  RobotPositionResponse_()
    : status(0)
    , x(0.0)
    , y(0.0)  {
    }
  RobotPositionResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::explorer::RobotPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explorer::RobotPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotPositionResponse_

typedef ::explorer::RobotPositionResponse_<std::allocator<void> > RobotPositionResponse;

typedef boost::shared_ptr< ::explorer::RobotPositionResponse > RobotPositionResponsePtr;
typedef boost::shared_ptr< ::explorer::RobotPositionResponse const> RobotPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explorer::RobotPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explorer::RobotPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace explorer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'explorer': ['/home/fabrizio/ros_indigo_external/src/aau_multi_robot/explorer/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::explorer::RobotPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explorer::RobotPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer::RobotPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explorer::RobotPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer::RobotPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explorer::RobotPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explorer::RobotPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b39fc8def0c7ae32acff1997765ffe2";
  }

  static const char* value(const ::explorer::RobotPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b39fc8def0c7ae3ULL;
  static const uint64_t static_value2 = 0x2acff1997765ffe2ULL;
};

template<class ContainerAllocator>
struct DataType< ::explorer::RobotPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explorer/RobotPositionResponse";
  }

  static const char* value(const ::explorer::RobotPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explorer::RobotPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 status\n\
float32 x\n\
float32 y\n\
\n\
";
  }

  static const char* value(const ::explorer::RobotPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explorer::RobotPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explorer::RobotPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::explorer::RobotPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORER_MESSAGE_ROBOTPOSITIONRESPONSE_H
