// Generated by gencpp from file explorer/RobotPosition.msg
// DO NOT EDIT!


#ifndef EXPLORER_MESSAGE_ROBOTPOSITION_H
#define EXPLORER_MESSAGE_ROBOTPOSITION_H

#include <ros/service_traits.h>


#include <explorer/RobotPositionRequest.h>
#include <explorer/RobotPositionResponse.h>


namespace explorer
{

struct RobotPosition
{

typedef RobotPositionRequest Request;
typedef RobotPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotPosition
} // namespace explorer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::explorer::RobotPosition > {
  static const char* value()
  {
    return "23c69c8103af21e37240b074f5348b77";
  }

  static const char* value(const ::explorer::RobotPosition&) { return value(); }
};

template<>
struct DataType< ::explorer::RobotPosition > {
  static const char* value()
  {
    return "explorer/RobotPosition";
  }

  static const char* value(const ::explorer::RobotPosition&) { return value(); }
};


// service_traits::MD5Sum< ::explorer::RobotPositionRequest> should match 
// service_traits::MD5Sum< ::explorer::RobotPosition > 
template<>
struct MD5Sum< ::explorer::RobotPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::explorer::RobotPosition >::value();
  }
  static const char* value(const ::explorer::RobotPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::explorer::RobotPositionRequest> should match 
// service_traits::DataType< ::explorer::RobotPosition > 
template<>
struct DataType< ::explorer::RobotPositionRequest>
{
  static const char* value()
  {
    return DataType< ::explorer::RobotPosition >::value();
  }
  static const char* value(const ::explorer::RobotPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::explorer::RobotPositionResponse> should match 
// service_traits::MD5Sum< ::explorer::RobotPosition > 
template<>
struct MD5Sum< ::explorer::RobotPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::explorer::RobotPosition >::value();
  }
  static const char* value(const ::explorer::RobotPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::explorer::RobotPositionResponse> should match 
// service_traits::DataType< ::explorer::RobotPosition > 
template<>
struct DataType< ::explorer::RobotPositionResponse>
{
  static const char* value()
  {
    return DataType< ::explorer::RobotPosition >::value();
  }
  static const char* value(const ::explorer::RobotPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXPLORER_MESSAGE_ROBOTPOSITION_H
