// Generated by gencpp from file robot_state/GetRobotState.msg
// DO NOT EDIT!


#ifndef ROBOT_STATE_MESSAGE_GETROBOTSTATE_H
#define ROBOT_STATE_MESSAGE_GETROBOTSTATE_H

#include <ros/service_traits.h>


#include <robot_state/GetRobotStateRequest.h>
#include <robot_state/GetRobotStateResponse.h>


namespace robot_state
{

struct GetRobotState
{

typedef GetRobotStateRequest Request;
typedef GetRobotStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotState
} // namespace robot_state


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_state::GetRobotState > {
  static const char* value()
  {
    return "55dcb167b3a76ee9117eddcad656cf41";
  }

  static const char* value(const ::robot_state::GetRobotState&) { return value(); }
};

template<>
struct DataType< ::robot_state::GetRobotState > {
  static const char* value()
  {
    return "robot_state/GetRobotState";
  }

  static const char* value(const ::robot_state::GetRobotState&) { return value(); }
};


// service_traits::MD5Sum< ::robot_state::GetRobotStateRequest> should match 
// service_traits::MD5Sum< ::robot_state::GetRobotState > 
template<>
struct MD5Sum< ::robot_state::GetRobotStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_state::GetRobotState >::value();
  }
  static const char* value(const ::robot_state::GetRobotStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_state::GetRobotStateRequest> should match 
// service_traits::DataType< ::robot_state::GetRobotState > 
template<>
struct DataType< ::robot_state::GetRobotStateRequest>
{
  static const char* value()
  {
    return DataType< ::robot_state::GetRobotState >::value();
  }
  static const char* value(const ::robot_state::GetRobotStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_state::GetRobotStateResponse> should match 
// service_traits::MD5Sum< ::robot_state::GetRobotState > 
template<>
struct MD5Sum< ::robot_state::GetRobotStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_state::GetRobotState >::value();
  }
  static const char* value(const ::robot_state::GetRobotStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_state::GetRobotStateResponse> should match 
// service_traits::DataType< ::robot_state::GetRobotState > 
template<>
struct DataType< ::robot_state::GetRobotStateResponse>
{
  static const char* value()
  {
    return DataType< ::robot_state::GetRobotState >::value();
  }
  static const char* value(const ::robot_state::GetRobotStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_STATE_MESSAGE_GETROBOTSTATE_H
