// Generated by gencpp from file robot_state/LockRobotStateResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_STATE_MESSAGE_LOCKROBOTSTATERESPONSE_H
#define ROBOT_STATE_MESSAGE_LOCKROBOTSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_state
{
template <class ContainerAllocator>
struct LockRobotStateResponse_
{
  typedef LockRobotStateResponse_<ContainerAllocator> Type;

  LockRobotStateResponse_()
    : succeeded(false)  {
    }
  LockRobotStateResponse_(const ContainerAllocator& _alloc)
    : succeeded(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succeeded_type;
  _succeeded_type succeeded;




  typedef boost::shared_ptr< ::robot_state::LockRobotStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_state::LockRobotStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LockRobotStateResponse_

typedef ::robot_state::LockRobotStateResponse_<std::allocator<void> > LockRobotStateResponse;

typedef boost::shared_ptr< ::robot_state::LockRobotStateResponse > LockRobotStateResponsePtr;
typedef boost::shared_ptr< ::robot_state::LockRobotStateResponse const> LockRobotStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_state::LockRobotStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_state::LockRobotStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_state

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robot_state': ['/home/fabrizio/ros_indigo_external/src/aau_multi_robot/robot_state/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_state::LockRobotStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_state::LockRobotStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_state::LockRobotStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_state::LockRobotStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_state::LockRobotStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_state::LockRobotStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_state::LockRobotStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95e696a0d10686913abb262e0b4cbbcf";
  }

  static const char* value(const ::robot_state::LockRobotStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95e696a0d1068691ULL;
  static const uint64_t static_value2 = 0x3abb262e0b4cbbcfULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_state::LockRobotStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_state/LockRobotStateResponse";
  }

  static const char* value(const ::robot_state::LockRobotStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_state::LockRobotStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool succeeded\n\
\n\
";
  }

  static const char* value(const ::robot_state::LockRobotStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_state::LockRobotStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeeded);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LockRobotStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_state::LockRobotStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_state::LockRobotStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "succeeded: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeeded);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_STATE_MESSAGE_LOCKROBOTSTATERESPONSE_H
