// Generated by gencpp from file robot_state/LockRobotState.msg
// DO NOT EDIT!


#ifndef ROBOT_STATE_MESSAGE_LOCKROBOTSTATE_H
#define ROBOT_STATE_MESSAGE_LOCKROBOTSTATE_H

#include <ros/service_traits.h>


#include <robot_state/LockRobotStateRequest.h>
#include <robot_state/LockRobotStateResponse.h>


namespace robot_state
{

struct LockRobotState
{

typedef LockRobotStateRequest Request;
typedef LockRobotStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LockRobotState
} // namespace robot_state


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_state::LockRobotState > {
  static const char* value()
  {
    return "95e696a0d10686913abb262e0b4cbbcf";
  }

  static const char* value(const ::robot_state::LockRobotState&) { return value(); }
};

template<>
struct DataType< ::robot_state::LockRobotState > {
  static const char* value()
  {
    return "robot_state/LockRobotState";
  }

  static const char* value(const ::robot_state::LockRobotState&) { return value(); }
};


// service_traits::MD5Sum< ::robot_state::LockRobotStateRequest> should match 
// service_traits::MD5Sum< ::robot_state::LockRobotState > 
template<>
struct MD5Sum< ::robot_state::LockRobotStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_state::LockRobotState >::value();
  }
  static const char* value(const ::robot_state::LockRobotStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_state::LockRobotStateRequest> should match 
// service_traits::DataType< ::robot_state::LockRobotState > 
template<>
struct DataType< ::robot_state::LockRobotStateRequest>
{
  static const char* value()
  {
    return DataType< ::robot_state::LockRobotState >::value();
  }
  static const char* value(const ::robot_state::LockRobotStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_state::LockRobotStateResponse> should match 
// service_traits::MD5Sum< ::robot_state::LockRobotState > 
template<>
struct MD5Sum< ::robot_state::LockRobotStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_state::LockRobotState >::value();
  }
  static const char* value(const ::robot_state::LockRobotStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_state::LockRobotStateResponse> should match 
// service_traits::DataType< ::robot_state::LockRobotState > 
template<>
struct DataType< ::robot_state::LockRobotStateResponse>
{
  static const char* value()
  {
    return DataType< ::robot_state::LockRobotState >::value();
  }
  static const char* value(const ::robot_state::LockRobotStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_STATE_MESSAGE_LOCKROBOTSTATE_H
