// Generated by gencpp from file robot_state/SetRobotStateRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_STATE_MESSAGE_SETROBOTSTATEREQUEST_H
#define ROBOT_STATE_MESSAGE_SETROBOTSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_state
{
template <class ContainerAllocator>
struct SetRobotStateRequest_
{
  typedef SetRobotStateRequest_<ContainerAllocator> Type;

  SetRobotStateRequest_()
    : robot_state(0)  {
    }
  SetRobotStateRequest_(const ContainerAllocator& _alloc)
    : robot_state(0)  {
  (void)_alloc;
    }



   typedef int8_t _robot_state_type;
  _robot_state_type robot_state;




  typedef boost::shared_ptr< ::robot_state::SetRobotStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_state::SetRobotStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobotStateRequest_

typedef ::robot_state::SetRobotStateRequest_<std::allocator<void> > SetRobotStateRequest;

typedef boost::shared_ptr< ::robot_state::SetRobotStateRequest > SetRobotStateRequestPtr;
typedef boost::shared_ptr< ::robot_state::SetRobotStateRequest const> SetRobotStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_state::SetRobotStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_state::SetRobotStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_state

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robot_state': ['/home/fabrizio/ros_indigo_external/src/aau_multi_robot/robot_state/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_state::SetRobotStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_state::SetRobotStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_state::SetRobotStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_state::SetRobotStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_state::SetRobotStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_state::SetRobotStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_state::SetRobotStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0e33302e4133a2df1d5811533e3c8e1";
  }

  static const char* value(const ::robot_state::SetRobotStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0e33302e4133a2dULL;
  static const uint64_t static_value2 = 0xf1d5811533e3c8e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_state::SetRobotStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_state/SetRobotStateRequest";
  }

  static const char* value(const ::robot_state::SetRobotStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_state::SetRobotStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 robot_state\n\
";
  }

  static const char* value(const ::robot_state::SetRobotStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_state::SetRobotStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobotStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_state::SetRobotStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_state::SetRobotStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.robot_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_STATE_MESSAGE_SETROBOTSTATEREQUEST_H
