(cl:defpackage robot_state-srv
  (:use )
  (:export
   "LOCKROBOTSTATE"
   "<LOCKROBOTSTATE-REQUEST>"
   "LOCKROBOTSTATE-REQUEST"
   "<LOCKROBOTSTATE-RESPONSE>"
   "LOCKROBOTSTATE-RESPONSE"
   "GETROBOTSTATE"
   "<GETROBOTSTATE-REQUEST>"
   "GETROBOTSTATE-REQUEST"
   "<GETROBOTSTATE-RESPONSE>"
   "GETROBOTSTATE-RESPONSE"
   "UNLOCKROBOTSTATE"
   "<UNLOCKROBOTSTATE-REQUEST>"
   "UNLOCKROBOTSTATE-REQUEST"
   "<UNLOCKROBOTSTATE-RESPONSE>"
   "UNLOCKROBOTSTATE-RESPONSE"
   "SETROBOTSTATE"
   "<SETROBOTSTATE-REQUEST>"
   "SETROBOTSTATE-REQUEST"
   "<SETROBOTSTATE-RESPONSE>"
   "SETROBOTSTATE-RESPONSE"
  ))

